Site search improvements
lucidworks/searchhub pull request #125
Opened 2017-01-27 02:58 UTC by yannyu

Minor fixes to query pipelines and *:* queries

2017-01-27 03:11 UTC, gsingers requested changes
Overall looks good.  Check again for consistency across a few places.

2017-01-27 03:11 UTC, gsingers commented on python/fusion_config/query_default_pipeline.json
> +          "value": "id title productVersion productName og_image parent_s author project_label datasource_label",
@yannyu why the two different "fl" settings.  The "Query Fields" stage has a "return fields" setting.  Add them there.

2017-01-27 03:11 UTC, gsingers commented on python/fusion_config/query_site_search_all_pipeline.json
> +    "condition" : "request.getFirstParam(\"q\") == \"*\" || request.getFirstParam(\"q\") == \"*:*\""
How's the performance of this look?

2017-01-27 03:11 UTC, gsingers commented on python/fusion_config/query_site_search_blog_pipeline.json
> +      "key": "mm.autoRelax",
We need to set the `mm` value on the Query Fields Stage (scroll to the bottom)

2017-01-27 03:11 UTC, gsingers commented on python/fusion_config/query_site_search_documentation_pipeline.json
> +        "value": "true",
Same about the `mm` setting.

2017-01-27 03:11 UTC, gsingers commented on python/fusion_config/query_site_search_videos_pipeline.json
> +      "key": "mm.autoRelax",
Same about mm

2017-01-27 03:20 UTC, yannyu commented on python/fusion_config/query_site_search_all_pipeline.json
> +    "condition" : "request.getFirstParam(\"q\") == \"*\" || request.getFirstParam(\"q\") == \"*:*\""
It's only the * query for each page, so it's not bad and caches well.

2017-01-27 18:37 UTC, gsingers commented on python/fusion_config/query_default_pipeline.json
> +          "value" : "title content body subject accepted_answer_txt answer_txt",
We prob. should highlight in the ?_text too?

2017-01-27 18:37 UTC, gsingers commented on python/fusion_config/query_site_search_all_pipeline.json
> +    "type" : "set-params",
Can this be a Query Fields Stage?

2017-01-27 18:37 UTC, gsingers commented on python/fusion_config/query_site_search_blog_pipeline.json
> +    "type" : "set-params",
Same as above, can this be a Query Fields Stage?

2017-01-27 18:37 UTC, gsingers commented on python/fusion_config/query_site_search_documentation_pipeline.json
> +      "value" : "title content body subject accepted_answer_txt answer_txt",
Again.

2017-01-27 18:37 UTC, gsingers commented on python/fusion_config/query_site_search_videos_pipeline.json
> +      "value" : "title content body subject accepted_answer_txt answer_txt",
here too

2017-01-29 03:21 UTC, yannyu commented on python/fusion_config/query_site_search_all_pipeline.json
> +    "type" : "set-params",
The Query Fields stage lets you put in qf and fl params, not sure how we'd shoehorn in these grouping params.

2017-01-29 03:23 UTC, yannyu commented on python/fusion_config/query_site_search_blog_pipeline.json
> +    "type" : "set-params",
Similarly, this is declaring fq params, not qf or fl.

2017-01-29 03:24 UTC, yannyu commented on python/fusion_config/query_site_search_documentation_pipeline.json
> +      "value" : "title content body subject accepted_answer_txt answer_txt",
And here we're declaring hl and hl.fl params, not standard fl params or qf params.

2017-01-30 03:40 UTC, merged